[package]
name = "test-helper"
version = "0.1.1"
edition = "2021"

[[bin]]
name = "test-helper"
path = "src/main.rs"

[dependencies]
assert-text = { path="../" }
regex = "1.11"

[dev-dependencies]
exec-target = "0.2"
rustversion = "1.0"

[build-dependencies]
